# Generated by Django 5.1.dev20240306045047 on 2024-03-12 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_post_date_posted_alter_post_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.RemoveField(
            model_name='post',
            name='author',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
