# Generated by Django 5.1.dev20240306045047 on 2024-03-13 06:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_post_delete_product'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('-published_in',)},
        ),
    ]
