# Generated by Django 5.1.dev20240306045047 on 2024-03-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_alter_post_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_in',
            field=models.DateField(auto_now_add=True),
        ),
    ]
