# Generated by Django 5.1.dev20240306045047 on 2024-03-17 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_postmodel_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmodel',
            name='description',
            field=models.TextField(blank=True, default='', null=True),
        ),
    ]
